version: "3"

services:
  web:
    image: myjournal:1.3
    build: .
    ports:
      - "127.0.0.1:3001:3000"
    environment:  
      - NODE_ENV=production
      - MYJOURNAL_PASSWORD=123456
    links:
      - db
    restart: always

  db:
    image: mongo:3.4
    restart: always
